namespace ContextKing.Core.Search;

/// <summary>
/// The kind of symbol the agent is searching for. Determines which regex patterns
/// are generated by <see cref="ISearchPatternProvider"/>.
/// </summary>
public enum SearchType
{
    /// <summary>Class, interface, struct, record, or enum declaration.</summary>
    Class,

    /// <summary>Method or function declaration/call.</summary>
    Method,

    /// <summary>Property, field, or variable.</summary>
    Member,

    /// <summary>File name match only — no content grep.</summary>
    File,
}
